name = "highfly-bet-com-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=highfly-bet.com.es"
HMAC_KEY = "e158e6b70c5451ed1988f55108e528faad1b45d7e785fad5dffbbdd8ea2f9c16"
COOKIE_NAME = "2hl"
PLAY_PATH = "begin"
BUTTON_ID = "pac2efabbe035fb715f5dbe4968b63fb2"
GATE_SALT = "682e89ca639f467d"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "w16m"
CTA_SELECTOR = ".play-button"
